server:
  port: 7473

api:
  server:
    host: http://server:8095
    user: /v1/user

telegram:
  bot:
    name: SerialSubscribeBot
    token: 5240364048:AAFcpJL_bTkEERQQlIeYsO_7lA0iYnVaybg

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
